# This file is auto-generated from the current state of the database.
# Do not edit this file directly. Use migrations instead.

ActiveRecord::Schema[7.1].define(version: 0) do
  # No tables yet - add migrations as needed
end
