source "https://rubygems.org"
ruby "3.3.10"
gem "rails", "8.1.3.1"
gem "propshaft", "~> 1.3"
gem "pg", "~> 1.6"
gem "puma", "~> 7.2"
gem "dotenv", "~> 3.2"
# Rails 8.1's cookie decoder passes positional options unsupported by JSON 3.
gem "json", "~> 2.21"
gem "tzinfo-data", platforms: %i[windows jruby]
