export * from './Layout'
export * from './HeadTags'
export * from './HeroSection'
export * from './CTASection'
export * from './Pattern'
export * from './statelessDoneRightSection'
export * from './tryRenovationSection'
export * from './twoStrategiesSection'
