source 'https://rubygems.org'
ruby '3.2.8'

gem 'rails', '~> 7.1.0'
gem 'puma', '~> 6.0'
gem 'sqlite3', '~> 1.4'
gem 'bootsnap', require: false
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'

